name: Build and Publish Artifact
on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  

    - name: Restore dependencies
      run: dotnet restore ./test-site/test-site.csproj

    - name: Build project
      run: dotnet build ./test-site/test-site.csproj --configuration Release

    - name: Publish artifact
      run: dotnet publish ./test-site/test-site.csproj --configuration Release --output ./publish -r win-x64

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-site
        path: ./publish
